name: zen
description: Fedora Atomic spin for Asus Zenbook Duo

base-image: ghcr.io/ublue-os/base-main
image-version: 40

modules:
  - type: akmods
    base: asus
    # install:
      #- asus

  - type: bling
    install:
      - flatpaksync
      - laptop

  - type: files
    files:
      - usr: /usr 

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tokariew/glow/repo/fedora-%OS_VERSION%/tokariew-glow-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/himalaya/repo/fedora-%OS_VERSION%/atim-himalaya-fedora-%OS_VERSION%.repo 
      - https://copr.fedorainfracloud.org/coprs/mecattaf/catppuccin-theme/repo/fedora-%OS_VERSION%/mecattaf-catppuccin-theme-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mecattaf/libinput-gestures/repo/fedora-%OS_VERSION%/mecattaf-libinput-gestures-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

    install:
      - gcc-c++
      - gcc
      - make
      - mesa-libGLU
      - podman-compose
      - podman-tui
      - podmansh
      - hyprland
      - xdg-desktop-portal-hyprland
      - waybar
      - xorg-x11-server-Xwayland
      - xdg-user-dirs
      - android-tools
      - android-file-transfer
      - swaybg
      - swayidle
      - swaylock
      - tuned
      - tuned-utils
      - tuned-switcher
      - polkit-gnome
      - libseat
      - network-manager-applet
      - system-config-printer
      - firewall-config
      - blueman
      - thunar
      - thunar-archive-plugin
      - imv
      - kvantum
      - gnome-disk-utility
      - mako
      - xarchiver
      - pavucontrol
      - swappy
      - docker-compose
      - sddm
      - qt5ct
      - qt6ct
      - qt6-qtwayland
      - qt5-qtwayland
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      - grimshot
      - wdisplays
      - gnome-keyring
      - overpass-fonts
      - overpass-mono-fonts
      - google-noto-emoji-fonts
      - google-noto-fonts-common
      - google-roboto-fonts
      - google-noto-sans-fonts
      - light
      - fish
      - wtype
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-jack-audio-connection-kit
      - pipewire-pulseaudio
      - brightnessctl
      - polkit
      - lxpolkit
      - dbus-tools
      - dbus-daemon
      - wl-clipboard
      - playerctl
      - vulkan-validation-layers
      - vulkan-tools
      - bluez
      - bluez-tools
      - thunar-volman
      - p7zip
      - unrar-free
      - slurp
      - grim
      - wlr-randr
      - wlsunset
      - kanshi
      - adwaita-qt5
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - sddm-themes
      - python3-pip
      - python3-cairo
      - libadwaita
      - cpio
      - meson
      - cmake
      - starship
      - distrobox
      - polkit-kde
      - alacritty
      - kitty
      - kitty-terminfo
      - clipman
      - gammastep
      - remmina
      - wayvnc
      - neovim
      - ripgrep
      - pandoc
      - azote
      - wlogout
      - rofi-wayland
      - rofimoji
      - nwg-look
      - zathura
      - zathura-pdf-poppler
      - udiskie
      - NetworkManager-tui
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - stow
      - g++
      - mpd
      - mpc
      - mpdris2
      - ncmpcpp
      - sox
      - alsa-sof-firmware
      - glow
      - wf-recorder
      - wshowkeys
      - yt-dlp
      - aria2
      - bibata-cursor-themes
      - gsettings-desktop-schemas
      - tailscale
      - catppuccin-theme
      - himalaya
      - mesa-dri-drivers
      - mesa-vulkan-drivers
      - gvfs
      - gvfs-mtp
      - bolt
      - fprintd-pam
      - NetworkManager-openvpn
      - NetworkManager-openconnect
      - pamixer
      - wmctrl
      - ydotool
      - libinput-gestures

    remove:
      - firefox
      - firefox-langpacks
      - virtualbox-guest-additions
      - toolbox
      - nvtop

  - type: fonts
    nerd-fonts:
      - JetBrainsMono
      - Iosevka
      - NerdFontsSymbolsOnly


  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.google.Chrome
        - org.videolan.VLC
        - org.desmume.DeSmuME
        - io.mgba.mGBA
        - org.ppsspp.PPSSPP
        - com.hunterwittenborn.Celeste
        - it.mijorus.collector
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.OBSVkCapture
          #- org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          #- org.freedesktop.Platform.GStreamer.gstreamer-vaapi
      
  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - input-groupadd.service
        - tailscaled.service
      disabled:
        - rpm-ostree-countme.timer
        
  - type: script
    scripts:
      - settheming.sh
      - removeunprofessionalwallpapers.sh
      - sethyprlandwaybarmodules.sh 
      - setsddmtheming.sh
      - post-install.sh

  - type: chezmoi
    install_chezmoi: true 
    repository: "https://github.com/mecattaf/dots-zen"
    run_every: '1d' 
    wait_after_boot: '5m' 
    disable_init: false 
    disable_update: false 

  #Custom until merged
  #- type: brew
  #packages:
  #nofile-limits: true  # default: false
  #brew-analytics: true # default: true

  - type: signing
