name: zen
description: Fedora Atomic spin for Asus Zenbook Duo

base-image: ghcr.io/ublue-os/base-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/sway-tools/repo/fedora-%OS_VERSION%/tofik-sway-tools-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      #      - https://copr.fedorainfracloud.org/coprs/mecattaf/catppuccin-theme/repo/fedora-%OS_VERSION%/mecattaf-catppuccin-theme-fedora-%OS_VERSION%.repo
      #      - https://copr.fedorainfracloud.org/coprs/mecattaf/wl-gammarelay-rs/repo/fedora-%OS_VERSION%/mecattaf-wl-gammarelay-rs-fedora-%OS_VERSION%.repo
      #- https://copr.fedorainfracloud.org/coprs/sentry/kernel-fsync/repo/fedora-%OS_VERSION%/sentry-kernel-fsync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/xanderlent/intel-npu-driver/repo/fedora-%OS_VERSION%/xanderlent-intel-npu-driver-fedora-%OS_VERSION%.repo

    install:
      - gcc-c++
      - gcc
      - g++
      - make
      - mesa-libGLU
      - podman-compose
      - podman-tui
      - podmansh
      - docker-compose
      - sway
      - waybar
      - xorg-x11-server-Xwayland
      - xdg-user-dirs
      - swaybg
      - swayidle
      - swaylock
      - tuned
      - tuned-utils
      - tuned-switcher
      - mate-polkit # replaces polkit-gnome
      - network-manager-applet
      - system-config-printer
      - firewall-config
      - blueman
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - imv
      - gnome-disk-utility
      - mako
      - xarchiver
      - pavucontrol
      - swappy
      - docker-compose
      - sddm
      - qt5ct
      - qt6ct
      - qt6-qtwayland
      - qt5-qtwayland
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      - grimshot
      - gnome-keyring
      - overpass-fonts
      - overpass-mono-fonts
      - google-noto-emoji-fonts
      - google-noto-fonts-common
      - google-roboto-fonts
      - google-noto-sans-fonts
      - light
      - fish
      - wtype
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-jack-audio-connection-kit
      - pipewire-pulseaudio
      - brightnessctl
      - polkit
      - lxpolkit
      - lxqt-policykit
      - dbus-tools
      - dbus-daemon
      - wl-clipboard
      - playerctl
      - vulkan-validation-layers
      - vulkan-tools
      - bluez
      - bluez-tools
      - thunar-volman
      - p7zip
      - unrar-free
      - slurp
      - grim
      - wlr-randr
      - kanshi
      - adwaita-qt5
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - sddm-themes
      - python3-pip
      - python3-cairo
      - libadwaita
      - cpio
      - meson
      - cmake
      - starship
      - distrobox
      - polkit-kde
      - alacritty
      - kitty
      - kitty-terminfo
      - cliphist
      - nwg-clipman
      - remmina
      - wayvnc
      - neovim
      - ripgrep
      - pandoc
      - azote
      - wlogout
      - rofi-wayland
      - rofimoji
      - nwg-look
      - zathura
      - zathura-pdf-poppler
      - udiskie
      - NetworkManager-tui
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - sox
      - lame
      - alsa-sof-firmware
      - glow
      - mods
      - eza
      - wf-recorder
      - wshowkeys
      - yt-dlp
      - aria2
      - bibata-cursor-themes
      - gsettings-desktop-schemas
      - tailscale
      #      - catppuccin-theme
      - mesa-dri-drivers
      - mesa-vulkan-drivers
      - gvfs
      - gvfs-mtp
      - bolt
      - fprintd-pam
      - NetworkManager-openvpn
      - NetworkManager-openconnect
      - pamixer
      - wmctrl
      - ydotool
      #- wl-gammarelay-rs
      - python-autotiling
      # Intel ai basekit from https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&linux-install-type=dnf 
      # from yum.d
      - intel-basekit
      # from last COPR
      - intel-npu-level-zero
      # additional tools?
      - intel-opencl
      - libmfx
      - hwinfo
      - clinfo

    remove:
      - firefox
      - firefox-langpacks
      - virtualbox-guest-additions
      - toolbox
      - nvtop

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: script
    scripts:
      - install-ollama.sh

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - tailscaled.service
        - ollama-boot.service
        - ollama.service
      disabled:
        - rpm-ostree-countme.timer
        #user:
        # enabled:
        #- ollama.service
        #- ollama-web.service
        
  - type: script
    scripts:
      - setsddmtheming.sh
      - settheming.sh
      - post-install.sh
      #- fsync-kernel-override.sh

  - type: chezmoi
    install_chezmoi: true 
    repository: "https://github.com/mecattaf/dots-zen"
    run_every: '1d' 
    wait_after_boot: '5m' 
    disable_init: false 
    disable_update: false 

  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.google.Chrome
        - org.videolan.VLC
        - org.desmume.DeSmuME
        - io.mgba.mGBA
        - com.hunterwittenborn.Celeste
        - it.mijorus.collector
        - io.github.dvlv.boxbuddyrs
        - it.mijorus.gearlever
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - io.bassi.Amberol
          #- org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          #- org.freedesktop.Platform.GStreamer.gstreamer-vaapi

    #  - type: brew
    #    nofile-limits: true
    #    brew-analytics: false

  - type: signing
