name: zen
description: Fedora Atomic spin for Asus Zenbook Duo

base-image: ghcr.io/ublue-os/base-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Base system components
  - from-file: recipes/base/system-core.yml
  - from-file: recipes/base/wayland-environment.yml
  - from-file: recipes/base/desktop-apps.yml
  - from-file: recipes/base/login-manager.yml
  - from-file: recipes/base/intel-support.yml
  - from-file: recipes/base/system-portals.yml
  - from-file: recipes/base/media-hardware.yml
  - from-file: recipes/base/fonts-themes.yml
  # COPR repositories
  - from-file: recipes/copr/starship.yml
  - from-file: recipes/copr/zenrpm.yml
  - from-file: recipes/copr/intel-npu.yml
  # YUM repositories
  - from-file: recipes/yum/charm.yml
  - from-file: recipes/yum/intel-basekit.yml
  - from-file: recipes/yum/tailscale.yml

  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - virtualbox-guest-additions
      - toolbox
      - nvtop

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: script
    scripts:
      - install-ollama.sh

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - tailscaled.service
        - ollama-boot.service
        - ollama.service
      disabled:
        - rpm-ostree-countme.timer
        #user:
        # enabled:
        #- ollama.service
        #- ollama-web.service
        
  - type: script
    scripts:
      - setsddmtheming.sh
      - settheming.sh
      - post-install.sh
      #- fsync-kernel-override.sh

  - type: chezmoi
    install_chezmoi: true 
    repository: "https://github.com/mecattaf/dots-zen"
    run_every: '1d' 
    wait_after_boot: '5m' 
    disable_init: false 
    disable_update: false 

  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.google.Chrome
        - org.videolan.VLC
        - org.desmume.DeSmuME
        - io.mgba.mGBA
        - com.hunterwittenborn.Celeste
        - it.mijorus.collector
        - io.github.dvlv.boxbuddyrs
        - it.mijorus.gearlever
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - io.bassi.Amberol
          #- org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          #- org.freedesktop.Platform.GStreamer.gstreamer-vaapi

    #  - type: brew
    #    nofile-limits: true
    #    brew-analytics: false

  - type: signing
