type: rpm-ostree
install:
  - azote
  - grimshot
  - grim
  - kanshi
  - light
  - mako
  - playerctl
  - rofi-wayland
  - rofimoji
  - slurp
  - sway
  - swaybg
  - swayidle
  - swaylock
  - waybar
  - wf-recorder
  - wl-clipboard
  - wlogout
  - wlr-randr
  - wshowkeys
  - wtype
  - xorg-x11-server-Xwayland
